// Generated by delombok at Tue Jul 19 16:55:45 ICT 2022
package sample.PensionFund.sources;

import java.util.Arrays;
import java.util.List;

public class PensionFundController {
    private List<PensionFundTab> tabs;
    private int selectedTabIndex;

    public PensionFundController() {
        this.initTabs();
    }


    public enum PensionFundTab {
        PENSION_FUND_EXPORT, PENSION_FUND_IMPORT;
    }

    private void initTabs() {
        this.tabs = Arrays.asList(PensionFundTab.values());
    }

    public boolean isTabSelected(String tabName) {
        return this.isTabSelected(PensionFundTab.valueOf(tabName));
    }

    private boolean isTabSelected(PensionFundTab tab) {
        return this.selectedTabIndex == this.tabs.indexOf(tab);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<PensionFundTab> getTabs() {
        return this.tabs;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getSelectedTabIndex() {
        return this.selectedTabIndex;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTabs(final List<PensionFundTab> tabs) {
        this.tabs = tabs;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSelectedTabIndex(final int selectedTabIndex) {
        this.selectedTabIndex = selectedTabIndex;
    }
}
